import json
import re
from LunarLander_v3_heuristics import HEURISTICS, get_heuristic_by_text

class LLMRouter:
    def __init__(self, curriculum_buffer, ssl_buffer, global_buffer=None, example_buffer=None, metrics=None):
        self.curriculum_buffer = curriculum_buffer
        self.ssl_buffer = ssl_buffer
        self.global_buffer = global_buffer
        self.example_buffer = example_buffer
        self.metrics = metrics

    def process(self, item):
        """Processes a single item from the LLMBuffer (Classify then Commit)."""
        classification = self.classify(item)
        if classification:
            return self.commit(item, classification)
        return None

    def classify(self, item):
        """Classifies a single item without pushing to buffers."""
        return self._mock_llm_classify(item['note_text'], item['current_obs_dict'])

    def commit(self, item, classification, verification_trajectory=None):
        """Commits a classification by pushing to curriculum or SSL buffers."""
        # Extract historical actions up to the note_frame_idx (exclude dummy action at index 0)
        historical_actions = [step['action'] for step in item['episode_trajectory'][1:item['note_frame_idx'] + 1]]
        
        if classification['type'] == 'GENERIC':
            self.curriculum_buffer.push(
                seed=item['seed'],
                start_frame=item['note_frame_idx'],
                trajectory_length=50, 
                reward_function_callable=lambda obs, next_obs, r: r,
                historical_actions=historical_actions
            )
        elif classification['type'] == 'GOAL':
            reward_fn = self._create_reward_fn(classification['code'])
            self.curriculum_buffer.push(
                seed=item['seed'],
                start_frame=item['note_frame_idx'],
                trajectory_length=100,
                reward_function_callable=reward_fn,
                historical_actions=historical_actions
            )
        elif classification['type'] == 'HEURISTIC':
            # R4.2 & Paper Telemetry: 
            # Only store the PRISTINE trajectory human just approved.
            # Only NEW frames generated here count as interactions.
            
            term_rule = classification.get('termination_rule')
            committed_count = 0
            
            # 1. Push only frames from the human-verified trajectory
            if verification_trajectory:
                # Find the starting point (annotation frame)
                start_idx = item['note_frame_idx']
                # Only push the part that was generated by the heuristic
                for step in verification_trajectory[start_idx:]:
                    if step.get('source') == 'heuristic':
                        self.ssl_buffer.push(
                            step['obs'], 
                            step['action'], 
                            classification['feature_mask'], 
                            termination_rule=term_rule
                        )
                        committed_count += 1
                        # Log ONLY these as new interactions
                        if self.metrics: self.metrics.log_frames(1, source="ssl")

            # Store metadata for dynamic mining during training
            classification['committed_frames'] = committed_count
            print(f"[SSL Commitment] Added {committed_count} pristine verified frames for heuristic: {classification.get('name', 'Unknown')}")
            
        return classification

    def _mock_llm_classify(self, text, obs):
        """
        Mocks LLM classification logic with specific keywords.
        Reference LunarLander-V3.md for qualitative magnitudes.
        """
        text = text.lower()
        
        # --- 1. Check Heuristics Library First (SSL) ---
        h_name, h_data = get_heuristic_by_text(text)
        if h_data:
            action = h_data.get('action')
            # Dynamic action assignment for direction-dependent rules
            if action is None and h_data.get('action_fn') is None:
                if h_name == "UNRECOVERABLE_SPIN_PREVENTION":
                    ang_vel = obs['angular_vel']
                    action = 3 if ang_vel > 0 else 1 # If spinning left (+), rotate right (3)
                elif h_name == "DRIFT_CATCHER":
                    x_vel = obs['x_vel']
                    action = 1 if x_vel > 0 else 3 # If drifting right (+), rotate left (1)
            
            return {
                "type": "HEURISTIC",
                "name": h_name,
                "action": action,
                "action_fn": h_data.get('action_fn'),
                "feature_mask": h_data['feature_mask'],
                "rule": h_data['trigger_rule'],
                "termination_rule": h_data['termination_rule'],
                "phrase": h_data['phrase']
            }

        # --- 2. GOALS (Reward Functions) ---
        if "gain stability" in text or "gain control" in text:
            return {
                "type": "GOAL",
                "code": "def custom_reward(obs, next_obs, base_r):\n    # Penalize velocity and angular velocity to encourage stability\n    return base_r - 0.1 * (abs(next_obs[2]) + abs(next_obs[3]) + abs(next_obs[5]))"
            }
        if "straighten out" in text:
            return {
                "type": "GOAL",
                "code": "def custom_reward(obs, next_obs, base_r):\n    # Penalize linear velocities (x, y), tilt angle, and rotation speed to kill drift\n    drift_penalty = 0.5 * (abs(next_obs[2]) + abs(next_obs[3]))\n    tilt_penalty = 0.5 * abs(next_obs[4]) + 0.1 * abs(next_obs[5])\n    return base_r - (drift_penalty + tilt_penalty)"
            }
        elif "hover down" in text:
            return {
                "type": "GOAL",
                "code": "def custom_reward(obs, next_obs, base_r):\n    target_vy = -0.3\n    stability_penalty = 0.5 * (abs(next_obs[2]) + abs(next_obs[4]) + abs(next_obs[5]))\n    speed_reward = -abs(next_obs[3] - target_vy)\n    return base_r + speed_reward - stability_penalty"
            }
        elif "hover left" in text:
            return {
                "type": "GOAL",
                "code": "def custom_reward(obs, next_obs, base_r):\n    target_vx = -0.3\n    stability_penalty = 0.5 * (abs(next_obs[3]) + abs(next_obs[5]))\n    speed_reward = -abs(next_obs[2] - target_vx)\n    return base_r + speed_reward - stability_penalty"
            }
        if "hover right" in text:
            return {
                "type": "GOAL",
                "code": "def custom_reward(obs, next_obs, base_r):\n    target_vx = 0.3\n    stability_penalty = 0.5 * (abs(next_obs[3]) + abs(next_obs[5]))\n    speed_reward = -abs(next_obs[2] - target_vx)\n    return base_r + speed_reward - stability_penalty"
            }
        elif "soft landing" in text:
            return {
                "type": "GOAL",
                "code": "def custom_reward(obs, next_obs, base_r):\n    # Reward low vertical velocity when close to ground\n    reward = base_r\n    if next_obs[1] < 0.2:\n        reward += 2.0 if abs(next_obs[3]) < 0.1 else -1.0\n    return reward"
            }
            
        # --- 3. Default Fallbacks ---
        if "reward" in text or "goal" in text:
            return {
                "type": "GOAL",
                "code": "def custom_reward(obs, next_obs, base_r):\n    return base_r + 10 if next_obs['y_vel'] > -0.1 else base_r - 1"
            }
        elif "look at" in text or "ignore" in text:
            return {
                "type": "HEURISTIC",
                "action": 0,
                "feature_mask": [0]
            }
        else:
            return {"type": "GENERIC"}

    def _create_reward_fn(self, code_string):
        """Safely evaluates a code string into a callable reward function."""
        # Extremely basic safety check
        if "import" in code_string or "eval" in code_string or "exec" in code_string:
            return lambda obs, next_obs, r: r
        
        try:
            local_vars = {}
            exec(code_string, {}, local_vars)
            # Find the first function defined in the code string
            for val in local_vars.values():
                if callable(val):
                    return val
        except Exception as e:
            print(f"Error evaluating reward function: {e}")
            
        return lambda obs, next_obs, r: r
